import { MedicamentoPrincipcio, MedicamentoIndicacion } from './';
import { ViaAdministracion } from './viaAdministracion';
import { Prescripcion } from './prescripcion';

export interface Medicine {
  id: number;
  ConOrden: number;
  TipoMed: number;
  TipoPrest: number;
  CausaS1: number;
  CausaS2: number;
  CausaS3: number;
  MedPBSUtilizado: number;
  RznCausaS31: number;
  DescRzn31: string;
  RznCausaS32: number;
  DescRzn32: string;
  CausaS4: number;
  MedPBSDescartado: string;
  RznCausaS41: number;
  DescRzn41: string;
  RznCausaS42: number;
  DescRzn42: string;
  RznCausaS43: number;
  DescRzn43: string;
  RznCausaS44: number;
  DescRzn44: string;
  CausaS5: number;
  RznCausaS5: number;
  CausaS6: number;
  DescMedPrinAct: string;
  CodFF: string;
  CodVA: string;
  JustNoPBS: string;
  Dosis: string;
  DosisUM: string;
  NoFAdmon: string;
  CodFreAdmon: number;
  IndEsp: number;
  CanTrat: string;
  DurTrat: number;
  CantTotalF: string;
  UFCantTotal: string;
  IndRec: string;
  EstJM: number;
  prescripcionId: number;
  indEntregado: boolean;
  PrincipiosActivos: MedicamentoPrincipcio[];
  IndicacionesUNIRS: MedicamentoIndicacion[];
  viaAdministracion: ViaAdministracion;
  Prescripcion: Prescripcion;
}
